#ifndef MK1MF_BUILD
    /* auto-generated by util/mkbuildinf.pl for crypto/cversion.c */
    #define CFLAGS cflags
    /*
     * Generate CFLAGS as an array of individual characters. This is a
     * workaround for the situation where CFLAGS gets too long for a C90 string
     * literal
     */
    static const char cflags[] = {
        'c','o','m','p','i','l','e','r',':',' ','g','c','c',' ','-','I','.',' ',
        '-','I','.','.',' ','-','I','.','.','/','i','n','c','l','u','d','e',' ',
        '-','I','i','n','c','l','u','d','e',' ',' ','-','D','O','P','E','N','S',
        'S','L','_','T','H','R','E','A','D','S',' ','-','D','_','R','E','E','N',
        'T','R','A','N','T',' ','-','D','G','E','T','P','I','D','_','I','S','_',
        'M','E','A','N','I','N','G','L','E','S','S','a',' ','-','m','6','4',' ',
        '-','D','L','_','E','N','D','I','A','N',' ','-','W','a','l','l',' ','-',
        'O','3',' ','-','f','P','I','C','\0'
    };
    #define PLATFORM "platform: linux-x86_64"
    #define DATE "built on: Fri Nov 25 04:33:13 2016"
#endif
