erase ..\nodes\A001\logs\notice.log
erase ..\nodes\A001\logs\info.log
erase ..\nodes\A002\logs\notice.log
erase ..\nodes\A002\logs\info.log
erase ..\nodes\A003\logs\notice.log
erase ..\nodes\A003\logs\info.log
erase ..\nodes\R001\logs\notice.log
erase ..\nodes\R001\logs\info.log
erase ..\nodes\R002\logs\notice.log
erase ..\nodes\R002\logs\info.log
erase ..\nodes\R003\logs\notice.log
erase ..\nodes\R003\logs\info.log
erase ..\nodes\C001\logs\notice.log
erase ..\nodes\C001\logs\info.log