erase C:\Users\INA-SGX-USER\Desktop\TorVS2012\nodes\A001\logs\notice.log
erase C:\Users\INA-SGX-USER\Desktop\TorVS2012\nodes\A001\logs\info.log
erase C:\Users\INA-SGX-USER\Desktop\TorVS2012\nodes\A002\logs\notice.log
erase C:\Users\INA-SGX-USER\Desktop\TorVS2012\nodes\A002\logs\info.log
erase C:\Users\INA-SGX-USER\Desktop\TorVS2012\nodes\A003\logs\notice.log
erase C:\Users\INA-SGX-USER\Desktop\TorVS2012\nodes\A003\logs\info.log
erase C:\Users\INA-SGX-USER\Desktop\TorVS2012\nodes\R001\logs\notice.log
erase C:\Users\INA-SGX-USER\Desktop\TorVS2012\nodes\R001\logs\info.log
erase C:\Users\INA-SGX-USER\Desktop\TorVS2012\nodes\R002\logs\notice.log
erase C:\Users\INA-SGX-USER\Desktop\TorVS2012\nodes\R002\logs\info.log
erase C:\Users\INA-SGX-USER\Desktop\TorVS2012\nodes\R003\logs\notice.log
erase C:\Users\INA-SGX-USER\Desktop\TorVS2012\nodes\R003\logs\info.log
erase C:\Users\INA-SGX-USER\Desktop\TorVS2012\nodes\C001\logs\notice.log
erase C:\Users\INA-SGX-USER\Desktop\TorVS2012\nodes\C001\logs\info.log